# render.yaml
services:
  # База данных PostgreSQL
  - type: psql
    name: plotix-db
    databaseName: plotix_db # Название вашей БД
    user: plotix_user   # Имя пользователя
    plan: free # Используем бесплатный тариф
    # Укажите версию PostgreSQL, если это важно
    # postgresqlVersion: 14

  # Backend на FastAPI
  - type: web
    name: plotix-backend
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Ссылка на ваш репозиторий
    # Укажите путь к Dockerfile, если он не в корне
    dockerfilePath: ./backend/Dockerfile # Примерный путь
    plan: free
    # Переменные окружения для бэкенда
    envVars:
      - key: DATABASE_URL
        # Render автоматически создаст эту переменную из сервиса psql
        fromService:
          type: psql
          name: plotix-db
          property: connectionString
      - key: SECRET_KEY # И другие ваши секреты
        sync: false # Чтобы не хранить в Git, а ввести в UI

  # Frontend на Vue.js (собранный через Nginx)
  - type: web
    name: plotix-frontend
    env: docker
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME # Тот же репозиторий
    dockerfilePath: ./frontend/Dockerfile # Примерный путь
    plan: free
    envVars:
      # Указываем фронтенду, по какому адресу находится бэкенд
      - key: VITE_API_BASE_URL # или как у вас называется переменная
        fromService:
          type: web
          name: plotix-backend
          property: url